pipeline{
    agent any
    stages{
        stage('Git pull'){
            steps{
                script{
                    def secret = withCredentials([string(credentailId:'my-secret')])
                    echo "Printing the secret from cedentials"
                    echo secret
                }
               
            }
        }
        stage('Npm install'){
            steps{
                echo 'Npm install preocess'
            }
        }
        stage("Build started"){
            steps{
                echo "Build completed...."
                echo "Another change here"
            }
        }
    }
}