pipeline{
    agent any
    environment{
        def secret = 'some useful text as def'
        def some = "so what is it"
    }
    options{
        //keep only the last 10 builds
        buildDiscarder(logRotator(numToKeepStr:'10'))
        // disable same jobs running in parallel
        disableConcurrentBuilds()      
        // timeout for whole pipeline in case of some step hanging
        // 300s:5 minute
        timeout(time: 300, unit: 'SECONDS')
    }
    stages{
        stage('NPM INSTALL'){
            when{
                branch 'main'
            }
            agent{
                docker{
                    image 'node:24'
                    reuseNode true
                }
            }
            steps{

               echo 'Running npm ci...' 
               sh '''
                    echo node --version
                    echo npm --version
                    npm ci
                '''
            }
        }
        stage('BUILD PROJECT'){
            agent{
                docker{
                    image 'node:24'
                }
            }
            steps{
                echo 'Build process started'
                sh '''
                    npm run build
                '''
            }
            
            post{
                success {
                    echo 'Build process completed!'
                }
                failure {
                    echo 'build failed...' 
                }
            }
        }
        stage("DEPLOYMENT"){
            steps{
                echo "Deployment ... "
                echo secret
            }
        }
    }
}