pipeline{
    agent any
    environment{
        def secret = 'some useful text as def'
        def some = credentials('my-secret')
    }
    stages{
        stage('Git pull'){
            steps{
               echo "${env.JENKINS_URL}"
               echo "${env.BUILD_ID}"
               echo "${secret}"
               echo some
            }
        }
        stage('Npm install'){
            steps{
                echo 'Npm install preocess'
            }
        }
        stage("Build started"){
            steps{
                echo "Build completed...."
                echo "Another change here"
            }
        }
    }
}